spring.application.name=backend
server.port=8081
# ==========================================
# CONFIGURACION DE POSTGRESQL (DATA SOURCE)
# ==========================================

spring.datasource.url=jdbc:postgresql://localhost:5432/club_ajedrez
spring.datasource.username=postgres
spring.datasource.password=ajedrez_123
spring.datasource.driver-class-name=org.postgresql.Driver


# ==========================================
# CONFIGURACION DE JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Esto soluciona de forma limpia el conflicto de la zona horaria con el driver y la base de datos
spring.jpa.properties.hibernate.jdbc.time_zone=UTC